repository: 678/678
repository_url: https://bbs.lq8.net/

timezone: Asia/Shanghai
lang: zh_CN

title: 六七导航 · 代码如诗
alias_en: 678
alias_cn: 六七导航
description: A Navigation Website for BYR
keywords: 六七八导航, 简单的导航
url: https://dh.lq8.net
established_at: "2016-10-01T00:00+08:00"

author: iROCKBUNNY
author_url: https://irockbunny.com
organization: TEELAB
organization_url: https://teelab.net
contact: contact[at]irockbunny[dot]com

image: https://bbs.lq8.net/data/attachment/forum/201812/11/175440jo64u64yncyow16z.jpg
logo: https://bbs.lq8.net/data/attachment/forum/201812/11/175440jo64u64yncyow16z.jpg
logo_dark: https://bbs.lq8.net/data/attachment/forum/201812/11/175440jo64u64yncyow16z.jpg
logo_white: https://bbs.lq8.net/data/attachment/forum/201812/11/175440jo64u64yncyow16z.jpg



plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor
theme: jekyll-theme-cayman
