repository: BYR-Navi/BYR-Navi
repository_url: https://bbs.lq8.net/

timezone: Asia/Shanghai
lang: zh_CN

title: 六七导航 · 代码如诗
alias_en: BYR-Navi
alias_cn: 六七导航
description: A Navigation Website for BYR
keywords: 六七八导航, 简单的导航
url: https://dh.lq8.net
established_at: "2016-10-01T00:00+08:00"

author: iROCKBUNNY
author_url: https://irockbunny.com
organization: TEELAB
organization_url: https://teelab.net
contact: contact[at]irockbunny[dot]com

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo-dark.svg
logo_white: /images/logo-white.svg

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor
theme: jekyll-theme-cayman
